CREATE TABLE CLIENT (
	ID UUID DEFAULT RANDOM_UUID() NOT NULL,
	NAME CHARACTER VARYING(50) NOT NULL,
	PHONE_NUMBER CHARACTER(11),
	BIRTH_AT CHARACTER(8),
	PHOTO_SHOT UUID,
	MEMBER_ID INTEGER,
	CABINET SMALLINT,
	EXPIRED_AT CHARACTER(8),
	CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT CONSTRAINT_CLIENT PRIMARY KEY (ID,NAME)
);